# Generated by Django 3.2.19 on 2023-05-20 16:46

from django.db import migrations, models
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_no', models.IntegerField()),
                ('view_type', models.CharField(choices=[('ocean', 'Ocean'), ('mountain', 'Mountain'), ('garden', 'Garden')], default='ocean', max_length=50)),
                ('capacity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('description', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='rooms/')),
                ('image_alt', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-capacity'],
            },
        ),
    ]
