# Generated by Django 3.2.19 on 2023-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='main_guest_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
